//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLig_Codefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrenors
    {
        public int AntrenorId { get; set; }
        public string AntrenorAdi { get; set; }
        public int Yas { get; set; }
        public string TakimI { get; set; }
        public string Ulke { get; set; }
    }
}
