//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLig_Codefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string OynadigiTakim { get; set; }
        public int Yas { get; set; }
        public int FormaNumarasi { get; set; }
        public Nullable<int> Takims_TakimId { get; set; }
    
        public virtual Takims Takims { get; set; }
    }
}
